### ISSUE TITLE
Update GHZ Game on real devices

### ISSUE THREAD

**Issue by vabarbosa** [vabarbosa/Fun-with-Quantum#5]
The [GHZ Game on real devices](https://github.com/vabarbosa/Fun-with-Quantum/blob/main/GHZ-on-Real-Devices.ipynb) notebook needs to be updated for Qiskit 1.2 and fix any broken links, typo, etc.

- [ ] Run through and update `GHZ-on-Real-Devices.ipynb` code cells
- [ ] Review and update `GHZ-on-Real-Devices.ipynb` content

Links
- [Qiskit 1.0 Migration Guide](https://docs.quantum.ibm.com/migration-guides)
- [Qiskit SDK release notes](https://docs.quantum.ibm.com/api/qiskit/release-notes)

**Comment by davidemoretti1** [comment]
working on it

**Comment by davidemoretti1** [comment]
@vabarbosa 
I met lots of problems on this notebook, I'll try to resume them in the best way:

1. `from qiskit.utils.mitigation import complete_meas_cal, CompleteMeasFitter` are not anymore supported, plus I'll explain in the following points why they are not useful anymore
2. First chapter **Comparing IBM quantum devices** use FakeBackends like FakeManila etc to do a comparison but the backends used Fake backend with only 5 qubits, I chose new fake backends mostly of 127 qubits, for obvious reasons -> they are much more accurate than the previous
3. Chapter 2 **Manually optimizing circuit**  it's something we don't do anymore and in fact the "optimized" circuit does 0.5% better but I have reasons to think it's random -> I would recommend to delete the chapter
4. Chapter 3 **Qiskit Transpiler Optimization** I would talk about the new primitives approach and mostly about the [pass manager](https://docs.quantum.ibm.com/guides/transpile-with-pass-managers) and the [new transpiler](https://docs.quantum.ibm.com/api/qiskit/transpiler) optimization levels etc.
5. chapter 4 **Measurement Error mitigation** I would talk about [error mitigation](https://docs.quantum.ibm.com/guides/configure-error-mitigation) and maybe error suppression but I need some advices here because I noticed the error mitigations are different from estimator and sampler and i think i got the difference between the two but I want some suggestions either way.

So as you can see the notebook, in my opinion and please let me know yours, it's to re-write. I can do it but it will take me some time. i think it's worth to know if there is already a notebook that present these themes so I don't do a duplicate. If you have any knowledge on this please let me know.

P.S.: I definitely think [this tutorial for transpilation](https://learning.quantum.ibm.com/tutorial/compare-transpiler-settings) may be very helpful, as I already said to you Va we need to remove `backend.run` from everywhere.

**Comment by JanLahmann** [comment]
Hi @davidemoretti1 , thanks a lot for the detailed review of this demo.
It was kind of expected that it is incompatible with Qiskit 1.x in its current form, and will need a number of changes.
The main purpose of the demo/notebook is education and highlighting important aspects when running circuits on a _real_ device (or a mock device) vs a perfect, noise-free simulator. It uses just three Qubits, but many effects of error and noise can be explained, and approaches to mitigate these.

Some comments on your specific remarks:
2. Yes, it might make sense to use current devices and their mock/fake versions. Please keep an eye on the aspects we want to highlight, e.g. swap gates might be necessary because of the coupling map and then add to the noise.    Question: do the results for new fake devices and the real devices match? (that would be nice, and show the accuracy of the noise model that is included in the fake devices) 
3.  Yes, such a manual optimization is not needed anymore. However, I think it is a nice illustration of the importance of choosing the best qubits of a device (which now can be done with transpire passes)
4. Yes, that should be updated.
5. For the GHZ game, we need to sample from a probability distribution (IIRC, we do just one shot), so only the sampler is applicable and not the estimator. That also implies that the typical error mitigation methods (ZNE, PEC) cannot be used as they only apply to the estimator. Maybe we can highlight the different optimization_levels, what techniques are applied in each of them and how the result (winning probability for the GHZ game) improves. In the original notebook, I found it very impressive how the winning odds can be improved from 70% or so to 95%.

**Comment by davidemoretti1** [comment]
Hi @JanLahmann and @vabarbosa ,

Sorry for being late. It has been quite full months among "normal" work and Quantum presentations and Qiskit Fall Fests..
So, I have quite updated the notebook, following Jan's suggestions I did the following changes:

1. as I said I updated the devices compared and used with the new ones and the ones available with the open plan
2. results in chapter 1,2,3 makes sense and are coherent with the ones of the old notebook, I kept the manual optimization as you suggested and in chapter 3 I emphasized the role of the optimization options of the transpiler
3. I just mentioned and did not went into details of the pass manager, since it is not useful for beginner notebooks like this and may over-complicate things for people who are learning. I mentioned it at the end of ch 3 and left the link to the docs though
4. I removed chapter 4 and 5, also the appendix where you left exercise for the student, since they were focus on manually optimizing the circuit and I don't think it's interesting, but this is definitely arguable, I just think applications and use cases are more worth spending time onto
5. instead of chapter 4 I compare what at beginning seemed a "better" system with respect to the "worst one" without optimized transpilation, to demonstrate that the optimization make the "worst" system a very good system, also better than the "best" ones (sorry bad explanation, it's better to read the notebook)
6. in the appendix I wrote the code necessary to run on the real hardware the circuit. maybe if an exercise is needed or preferred, I think this could be the one, leaving the student just the instructions to declare the real backend and leave the rest to complete!

NOTE: from the second circuit onward all the graph are doubled! it is very annoying and I tried everything to make them disappeared, maybe it's just my VSCode env, don't know, maybe @vabarbosa can help here...

I'll make a pull request now

**Comment by JanLahmann** [comment]
It looks great, @davidemoretti1 ! Thanks a lot!
I like the new chapter 4 "best system".
Would it make sense to contrast the results for fake_Kyiv and fake_Sherbrooke in that chapter (i.e. mention the concrete accuracy numbers for fake_kyiv again in this chapter)? I think that is pretty impressive.

**Comment by vabarbosa** [comment]
resolved by #17 #20 
thank you @davidemoretti1
